theme = 'hugo-theme-relearn'
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'APIOps with Kong Konnet and Insomnia'
[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
[params]
  themeVariant = "blue"
